### PR TITLE
Update to version 0.3.2 + fix

### PR DESCRIPTION
**Pull request by dbast**
https://github.com/conda-forge/vaex-jupyter-feedstock/pull/12 + fix

### CODE REVIEW

**Comment by dbast** [comment]
@maartenbreddels Ready for review / merge :)

**Comment by maartenbreddels** [comment]
Amazing, how did you do this? Does conda smithy do this?

**Comment by dbast** [comment]
What do you mean? I just forked the repo and added your existing update branch via second remote as starting point, added another commit, pushed that to the fork and created another PR :)

**Comment by maartenbreddels** [comment]
Ah, of course, I looked at the full diff, I now see you commit, looks good, many many thanks!

**Pull request merged**
